### ISSUE TITLE
Documentation examples

### ISSUE THREAD

**Issue by ghost** [modxcms/maxcdn#22]
A few common custom rules would be nice to see, like  "for example, only CDN cache assets in a certain folder or with a certain extension."

So suppose I only want to cache items in the /images/ and the /assets/ folders, or maybe only items with .js, .css and the standard image extensions.

**Comment by garryn** [comment]
There is a page in the GH wiki where I will add different examples as I encounter them on deployments. To be honest, the default rules satisfy most use cases but will keep an eye out for variations that may be useful for people.
