### ISSUE TITLE
Rules not firing

### ISSUE THREAD

**Issue by ChrisBane** [modxcms/maxcdn#23]
Hello, 
I'm have been unable to get the basic rules to fire.  Is this plugin compatible with rev v2.3?
https://github.com/modxcms/revolution/issues/11630

I have a pretty basic setup. the only thing that is different is that i'm using the EdgeSSL.  I changed the default url to the newer ssl version and i updated that url in each of the rules but it still will not fire.  I've also tried changing each of the rules to https and schemeless and neither worked.  Is there anything else i'm missing that i'll need to change to have this work with https?

Thanks

**Comment by garryn** [comment]
Sorry for not getting round to this sooner ... did you ever resolve your issues? I would be interested in your experiences using the component with custom EdgeSSL domains. As far as I'm aware, there should be no difference with using the component in that custom SSL scenario - we've successfully deployed this using the free SSL option provided by MaxCDN.

And yes, the component supports MODX Revo 2.2 and 2.3 (I've had a couple of recent deployments here on 2.3.3pl).

Perhaps a bit obvious, but did you check that 1) the rules were enabled and 2) the `mcdn.enabled` system setting was set to Yes?

**Comment by garryn** [comment]
Closing as this should now be fixed via 04a2c7c.
